fusion_file => MIP.csv (pour écrire MIP-fusion_file):
"SKU" : "MPN"_"Brand",
"Localized For" : écrire la valeur "fr_FR" de façon fixe,
"Title" : "MPN" "brand" "Type",
"Subtitle" : toujours vide, obligatoire,
"Product Description" : pour l'instant vide,
"Additional Info" : "Info complémentaire 1",
"Picture URL" : pour l'instant vide,
"ISBN" : pour l'instant vide,
"EAN" : pour l'instant vide,
"Marque": "Attribute Value 1",
"Type": "Attribute Value 2",
"OE": "Attribute Value 3" -> séparer les numéros OE avec un | et mettre maximum 65 numéros dans un champ Attribute Value, sinon en créer un nouveau à la suite
"MPN": "Attribute Value 4",
"Nombre de dents": "Attribute Value 5",
"Force d'éjection (N)": "Attribute Value 6",
"Poids": "Attribute Value 7",
"Fixation de colonne de direction": "Attribute Value 8",
"Diamètre du disque": "Attribute Value 9",
"Condition" : toujours écrire "NEW",
"Total Ship To Home Quantity" : "*Quantity",
"Channel ID" : écrire "EBAY_FR" de façon fixe,
"Category" : pour l'instant vide,
"Shipping Policy" : "*ShippingProfileName",
"Payment Policy" : "*PaymentProfileName",
"Return Policy" : "*ReturnProfileName",
"List Price" : "*StartPrice",
"VAT Percent" : toujours écrire 20,
"Max Quantity Per Buyer" : pour l'instant vide,
"Strikethrough Price" : pour l'instant vide,
"Store Category Name 1 " : pour l'instant vide,
"Include eBay Product Details" : toujours écrire FALSE,
"Template Name" : pour l'instant vide,
"Compatible Product 1" : "Ktype"